color: null
fieldLayouts:
  c79bb04b-c3e1-41bc-8317-6f316b85b1ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T09:06:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1f69a8f4-4b32-475d-b59b-6b4a2c83ff57
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:08:17+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 288cadfc-b407-4f0c-a9ca-e6ea1bff4b8b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:08:17+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 681a09c7-3e70-411d-8312-1a3e82acba0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff523976-40e1-4f92-a924-8d1e533b1a63
        userCondition: null
handle: categories
hasTitleField: true
icon: ''
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
