color: null
fieldLayouts:
  86196446-59e2-40b0-818c-60fd3f1b990c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T10:23:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 208da037-95cb-4cad-8075-f95fef1ca2a0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:24:37+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 328ff7b3-3954-4fb5-bffe-9e2e03fe6169
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e8255ac9-0ae8-4636-ac27-e33a4a63277e
        userCondition: null
handle: locations
hasTitleField: true
icon: ''
name: Locations
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
