defaultPlacement: end
enableVersioning: true
entryTypes:
  - bacf18ab-c118-4213-9c59-a04db477b8cc # Categories
handle: categories
maxAuthors: 1
name: Categories
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f6eaef1f-2f88-4856-8eee-c5ae9620f572: # Craft Template
    enabledByDefault: true
    hasUrls: true
    template: categories/_entry.twig
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: null
  uid: 7ae75d71-1553-4de4-963b-8cb98baf4d55
type: structure
